CREATE TABLE "churches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "churches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"image_url" text,
	"longitude" text,
	"latitude" text,
	"address" text,
	"email" text,
	"description" text,
	"link" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "churches_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "contact_submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contact_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" text NOT NULL,
	"subject" text NOT NULL,
	"description" text NOT NULL,
	"prayer_request" text,
	"support_email" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"church_id" integer NOT NULL,
	"profile_picture" text,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"middle_name" text,
	"gender" text NOT NULL,
	"birthdate" date NOT NULL,
	"year_joined" integer NOT NULL,
	"ministry_involvement" text,
	"occupation" text,
	"educational_attainment" text,
	"school" text,
	"degree" text,
	"mobile_number" text,
	"email" text,
	"home_address" text,
	"facebook_link" text,
	"x_link" text,
	"instagram_link" text,
	"tiktok_link" text,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_awards_recognitions" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"year" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_case_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"description" text NOT NULL,
	"year" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_children" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"name" text NOT NULL,
	"place_of_birth" text NOT NULL,
	"date_of_birth" timestamp NOT NULL,
	"gender" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_education_backgrounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"school_name" text NOT NULL,
	"educational_attainment" text NOT NULL,
	"date_graduated" timestamp,
	"description" text,
	"course" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_emergency_contacts" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"name" text NOT NULL,
	"relationship" text NOT NULL,
	"address" text NOT NULL,
	"contact_number" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_employment_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"company_name" text NOT NULL,
	"from_year" text NOT NULL,
	"to_year" text,
	"position" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_ministry_experiences" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"ministry_rank_id" integer NOT NULL,
	"description" text,
	"from_year" text NOT NULL,
	"to_year" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_ministry_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"church_location_id" integer NOT NULL,
	"from_year" text NOT NULL,
	"to_year" text,
	"contribution" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_ministry_skills" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"ministry_skill_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_seminars_conferences" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" serial NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"place" text,
	"year" text NOT NULL,
	"number_of_hours" serial NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ministers" (
	"id" serial PRIMARY KEY NOT NULL,
	"church_id" integer NOT NULL,
	"biography" text,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"middle_name" text,
	"suffix" text,
	"nickname" text,
	"date_of_birth" timestamp NOT NULL,
	"place_of_birth" text NOT NULL,
	"address" text NOT NULL,
	"gender" text NOT NULL,
	"height_feet" text NOT NULL,
	"weight_kg" text NOT NULL,
	"civil_status" text NOT NULL,
	"email" text,
	"telephone" text,
	"passport_number" text,
	"sss_number" text,
	"philhealth" text,
	"tin" text,
	"present_address" text NOT NULL,
	"permanent_address" text,
	"father_name" text NOT NULL,
	"father_province" text NOT NULL,
	"father_birthday" timestamp NOT NULL,
	"father_occupation" text NOT NULL,
	"mother_name" text NOT NULL,
	"mother_province" text NOT NULL,
	"mother_birthday" timestamp NOT NULL,
	"mother_occupation" text NOT NULL,
	"spouse_name" text,
	"spouse_province" text,
	"spouse_birthday" timestamp,
	"spouse_occupation" text,
	"wedding_date" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"skills" text,
	"hobbies" text,
	"sports" text,
	"other_religious_secular_training" text,
	"certified_by" text,
	"signature_image_url" text,
	"signature_by_certified_image_url" text,
	"image_url" text
);
--> statement-breakpoint
CREATE TABLE "ministry_ranks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ministry_ranks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ministry_ranks_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "ministry_skills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ministry_skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ministry_skills_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_church_id_churches_id_fk" FOREIGN KEY ("church_id") REFERENCES "public"."churches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_awards_recognitions" ADD CONSTRAINT "minister_awards_recognitions_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_case_reports" ADD CONSTRAINT "minister_case_reports_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_children" ADD CONSTRAINT "minister_children_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_education_backgrounds" ADD CONSTRAINT "minister_education_backgrounds_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_emergency_contacts" ADD CONSTRAINT "minister_emergency_contacts_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_employment_records" ADD CONSTRAINT "minister_employment_records_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_experiences" ADD CONSTRAINT "minister_ministry_experiences_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_experiences" ADD CONSTRAINT "minister_ministry_experiences_ministry_rank_id_ministry_ranks_id_fk" FOREIGN KEY ("ministry_rank_id") REFERENCES "public"."ministry_ranks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_records" ADD CONSTRAINT "minister_ministry_records_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_records" ADD CONSTRAINT "minister_ministry_records_church_location_id_churches_id_fk" FOREIGN KEY ("church_location_id") REFERENCES "public"."churches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_skills" ADD CONSTRAINT "minister_ministry_skills_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_skills" ADD CONSTRAINT "minister_ministry_skills_ministry_skill_id_ministry_skills_id_fk" FOREIGN KEY ("ministry_skill_id") REFERENCES "public"."ministry_skills"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_seminars_conferences" ADD CONSTRAINT "minister_seminars_conferences_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ministers" ADD CONSTRAINT "ministers_church_id_churches_id_fk" FOREIGN KEY ("church_id") REFERENCES "public"."churches"("id") ON DELETE no action ON UPDATE no action;