CREATE TABLE "churches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "churches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"image_url" text NOT NULL,
	"longitude" text NOT NULL,
	"latitude" text NOT NULL,
	"address" text NOT NULL,
	"email" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contact_submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contact_submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" text NOT NULL,
	"subject" text NOT NULL,
	"description" text NOT NULL,
	"prayer_request" text,
	"support_email" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_awards_recognitions" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"year" varchar(10) NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_children" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"place_of_birth" varchar(255) NOT NULL,
	"date_of_birth" date NOT NULL,
	"gender" varchar(10) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_education_backgrounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"school_name" varchar(255) NOT NULL,
	"educational_attainment" varchar(255) NOT NULL,
	"date_graduated" date,
	"description" text,
	"course" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_emergency_contacts" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"relationship" varchar(100) NOT NULL,
	"address" varchar(500) NOT NULL,
	"contact_number" varchar(50) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_employment_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"from_year" varchar(10) NOT NULL,
	"to_year" varchar(10) NOT NULL,
	"position" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_ministry_experiences" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"from_year" varchar(10) NOT NULL,
	"to_year" varchar(10),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_ministry_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"church_location_id" integer NOT NULL,
	"from_year" varchar(10) NOT NULL,
	"to_year" varchar(10),
	"contribution" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_ministry_skills" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"ministry_skill_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "minister_seminars_conferences" (
	"id" serial PRIMARY KEY NOT NULL,
	"minister_id" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"place" varchar(255),
	"year" varchar(10) NOT NULL,
	"number_of_hours" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ministers" (
	"id" serial PRIMARY KEY NOT NULL,
	"first_name" varchar(255) NOT NULL,
	"middle_name" varchar(255),
	"last_name" varchar(255) NOT NULL,
	"date_of_birth" date NOT NULL,
	"place_of_birth" varchar(255) NOT NULL,
	"gender" varchar(10) NOT NULL,
	"contact_number" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"address" varchar(500) NOT NULL,
	"nationality" varchar(100) NOT NULL,
	"civil_status" varchar(50) NOT NULL,
	"citizenship" varchar(100) NOT NULL,
	"father_name" varchar(255),
	"father_occupation" varchar(255),
	"mother_name" varchar(255),
	"mother_occupation" varchar(255),
	"spouse_name" varchar(255),
	"spouse_occupation" varchar(255),
	"spouse_date_of_birth" date,
	"spouse_place_of_birth" varchar(255),
	"spouse_nationality" varchar(100),
	"spouse_citizenship" varchar(100),
	"spouse_contact_number" varchar(50),
	"spouse_email" varchar(255),
	"ministry_status" varchar(100) NOT NULL,
	"role_in_church" varchar(255),
	"current_church" varchar(255),
	"home_church" varchar(255),
	"conversion_date" date,
	"water_baptism_date" date,
	"holy_ghost_baptism_date" date,
	"occupation" varchar(255),
	"company_name" varchar(255),
	"year_started" varchar(10),
	"image_url" varchar(500),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ministry_ranks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ministry_ranks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ministry_skills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ministry_skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "minister_awards_recognitions" ADD CONSTRAINT "minister_awards_recognitions_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_children" ADD CONSTRAINT "minister_children_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_education_backgrounds" ADD CONSTRAINT "minister_education_backgrounds_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_emergency_contacts" ADD CONSTRAINT "minister_emergency_contacts_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_employment_records" ADD CONSTRAINT "minister_employment_records_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_experiences" ADD CONSTRAINT "minister_ministry_experiences_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_records" ADD CONSTRAINT "minister_ministry_records_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_ministry_skills" ADD CONSTRAINT "minister_ministry_skills_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "minister_seminars_conferences" ADD CONSTRAINT "minister_seminars_conferences_minister_id_ministers_id_fk" FOREIGN KEY ("minister_id") REFERENCES "public"."ministers"("id") ON DELETE no action ON UPDATE no action;